### ISSUE TITLE
几篇相关的文章，建议加入

### ISSUE THREAD

**Issue by cvbhjkl** [baozjian/Top-Blockchain-paper#6]
NSDI2020
Fine-Grained Replicated State Machines for a Cluster Storage System
Ghostor: Toward a Secure Data-Sharing System from Decentralized Trust
这两篇标题虽然没有blockchain，但内容上都研究的是区块链关注的一些问题或者采用了一些基于区块链的方法。
INFOCOM2021也出来了。下面几篇是个人阅读后与区块链相关的文章
PROCESS: Privacy-Preserving On-Chain Certificate Status Service
Pyramid: A Layered Sharding Blockchain System
Leveraging Public-Private Blockchain Interoperability for Closed Consortium Interfacing
A Weak Consensus Algorithm and Its Application to High-Performance Blockchain
Code is the (F)Law: Demystifying and Mitigating Blockchain Inconsistency Attacks Caused by Software Bugs
TiBroco: A Fast and Secure Distributed Learning Framework for Tiered Wireless Edge Networks
A Consensus Protocol With Deterministic Finality
On the Performance of Pipelined HotStuff
Counter-Collusion Smart Contracts for Watchtowers in Payment Channel Networks

**Comment by baozjian** [comment]
收到，谢谢你，我最近整理以下~
